version: '3'

services:
  app:
    build: 
      context: ./app
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    command: >
      sh -c "gunicorn -w 2 -b 0:5000 --chdir /app/ app.wsgi:application"
  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on:
      - app